// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuotesMicroservice.Models;

namespace QuotesMicroservice.Migrations
{
    [DbContext(typeof(DemoContext))]
    [Migration("20210321060803_InitialModel1")]
    partial class InitialModel1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QuotesMicroservice.Models.Quotes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BussinessValueFrom")
                        .HasColumnType("int");

                    b.Property<int>("BussinessValueTo")
                        .HasColumnType("int");

                    b.Property<string>("PropertyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropertyValueFrom")
                        .HasColumnType("int");

                    b.Property<int>("PropertyValueTo")
                        .HasColumnType("int");

                    b.Property<int>("QuoteInsurance")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("QuotesList");
                });
#pragma warning restore 612, 618
        }
    }
}
